# -*- coding: utf-8 -*-
"""Streamlit Form.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHDuaPYX-qMuI1rGVwj1TQAvCQ97rui9
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st
st.title("Student Information Form")

name = st.text_input("Enter your name")

age = st.number_input("Enter your age")

course = st.selectbox(
    "Select Course",
    ["BCA","BBA","MBA","MCA"]
)

gender = st.radio(
    "Select Gender",
    ["Male","Female","Other"]
)

skills = st.multiselect(
    "Select your skills",
    ["Python", "Java", "C++", "AI", "Machine Learning"])

marks = st.slider(
    "Enter Marks",
    0,100
)

agree = st.checkbox(
    "I agree to terms"
)

if st.button("Submit"):

    st.write("Name:",name)
    st.write("Age:",age)
    st.write("Course:",course)
    st.write("Gender:",gender)
    st.write("Marks:",marks)
    st.write("Marks:",skills)

    if agree:
        st.success("Form Submitted")
    else:
        st.error("Please accept terms"
)